package cn.zhengzhaoyu.summerSemester.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMealOrder<M extends BaseMealOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setPlace(java.lang.Integer place) {
		set("place", place);
		return (M)this;
	}

	public java.lang.Integer getPlace() {
		return get("place");
	}

	public M setOrderText(java.lang.String orderText) {
		set("order_text", orderText);
		return (M)this;
	}

	public java.lang.String getOrderText() {
		return get("order_text");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
