package cn.zhengzhaoyu.summerSemester.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoom<M extends BaseRoom<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setRoomname(java.lang.String roomname) {
		set("roomname", roomname);
		return (M)this;
	}

	public java.lang.String getRoomname() {
		return get("roomname");
	}

	public M setFloor(java.lang.Integer floor) {
		set("floor", floor);
		return (M)this;
	}

	public java.lang.Integer getFloor() {
		return get("floor");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

}
