package cn.zhengzhaoyu.summerSemester.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTable<M extends BaseTable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSeat(java.lang.Integer seat) {
		set("seat", seat);
		return (M)this;
	}

	public java.lang.Integer getSeat() {
		return get("seat");
	}

	public M setBelong(java.lang.Integer belong) {
		set("belong", belong);
		return (M)this;
	}

	public java.lang.Integer getBelong() {
		return get("belong");
	}

}
