package cn.zhengzhaoyu.summerSemester.common.model;

import cn.zhengzhaoyu.summerSemester.common.model.base.BaseMeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Meal extends BaseMeal<Meal> {
	
}
