package cn.zhengzhaoyu.summerSemester.common.model;

import cn.zhengzhaoyu.summerSemester.common.model.base.BaseMealOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MealOrder extends BaseMealOrder<MealOrder> {
	
}
