package cn.zhengzhaoyu.summerSemester.common.model;

import cn.zhengzhaoyu.summerSemester.common.model.base.BaseRoomOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomOrder extends BaseRoomOrder<RoomOrder> {
	
}
