package cn.zhengzhaoyu.summerSemester.common.model;

import cn.zhengzhaoyu.summerSemester.common.model.base.BaseTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Table extends BaseTable<Table> {
	
}
