package cn.zhengzhaoyu.summerSemester.common.model;

import cn.zhengzhaoyu.summerSemester.common.model.base.BaseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {
	
}
